#pragma once

#include <string>
#include <cstdlib>
#include "root_dir.h" // This is a configuration file generated by CMake.

class FileSystem
{
private:
  typedef std::string (*Builder) (const std::string& path);

public:
  static std::string getPath(const std::string& path)
  {
    static std::string(*pathBuilder)(std::string const &) = getPathBuilder();
    return (*pathBuilder)(path);
  }

private:
  static std::string const & getRoot()
  {
    static std::string root = "";
    char* envPath = nullptr;
    size_t len = 0;
    errno_t err = _dupenv_s(&envPath, &len, "LOGL_ROOT_PATH");

    if (err == 0 && envPath != nullptr) {
        root = envPath;
        free(envPath);
    }
    else
    {
      root = logl_root;
    }

    return root;
  }

  //static std::string(*foo (std::string const &)) getPathBuilder()
  static Builder getPathBuilder()
  {
    if (getRoot() != "")
      return &FileSystem::getPathRelativeRoot;
    else
      return &FileSystem::getPathRelativeBinary;
  }

  static std::string getPathRelativeRoot(const std::string& path)
  {
    return getRoot() + std::string("/") + path;
  }

  static std::string getPathRelativeBinary(const std::string& path)
  {
    return "../../../" + path;
  }

};